spring.application.name=blinkit-analytics-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/blinkit_analytics
spring.datasource.username=postgres
spring.datasource.password=kimdokja

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect